from activitytracker import views
from django.contrib.auth import views as auth_views
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.routers import DefaultRouter
from activitytracker.views import RegisterView, login_view, get_csrf_token, ActivityRetrieveUpdateDestroyView
from .views import home, about, dashboard, activity_log

# Set up the router for ViewSets
router = DefaultRouter()
router.register(r'activities', ActivityRetrieveUpdateDestroyView, basename='activity')

# Define URL patterns
urlpatterns = [
    # Include routes generated by the router
    path('api/', include(router.urls)),

    # Other API endpoints
    path("api/get_csrf_token/", get_csrf_token, name="get_csrf_token"),
    path("api/register/", RegisterView.as_view(), name="user_registration"),
    path("api/login/", login_view, name="login"),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),

    # Frontend routes
    path("", home, name="home"),
    path("about/", about, name="about"),
    path("dashboard/", dashboard, name="dashboard"),
    path("register/", views.register, name="register"),

    # Authentication-related routes
    path("accounts/logout/", auth_views.LogoutView.as_view(next_page="home"), name="logout"),
    path("accounts/register/", RegisterView.as_view(), name="account_register"),
    path("accounts/profile/", views.profile, name="profile"),
    path("activity-log/", activity_log, name="activity-log"),
    path("update/<int:pk>/", views.update_activity, name="update_activity"),
    path("delete_activity/<int:pk>/", views.delete_activity, name="delete_activity"),


]
