# Generated by Django 5.1.5 on 2025-01-26 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('walking', 'Walking'), ('hiking', 'Hiking'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('strength_training', 'Strength Training')], max_length=20)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('duration_interval', models.DurationField(blank=True, help_text='Duration in hh:mm:ss', null=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the activity', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excerpt', models.TextField(blank=True)),
                ('activity_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
