# Generated by Django 5.1.5 on 2025-06-14 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("walking", "Walking"),
                            ("hiking", "Hiking"),
                            ("running", "Running"),
                            ("cycling", "Cycling"),
                            ("swimming", "Swimming"),
                            ("strength_training", "Strength Training"),
                            ("yoga", "Yoga"),
                            ("crossfit", "CrossFit"),
                            ("dancing", "Dancing"),
                            ("gym", "Gym"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        help_text="Duration of activity in hh:mm:ss format"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        help_text="Duration of activity in seconds", null=True
                    ),
                ),
                ("date", models.DateField()),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the activity",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("excerpt", models.TextField(blank=True)),
                (
                    "activity_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="activitytracker.activity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChangeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_description", models.TextField()),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_history",
                        to="activitytracker.activity",
                    ),
                ),
            ],
        ),
    ]
