# Generated by Django 4.2.18 on 2025-01-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitytracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
