# Generated by Django 5.1.5 on 2025-06-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activitytracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="duration_seconds",
        ),
        migrations.AlterField(
            model_name="activity",
            name="duration",
            field=models.IntegerField(help_text="Duration of activity in seconds"),
        ),
    ]
