# Generated by Django 5.1.5 on 2025-01-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitytracker', '0002_activity_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
