# Generated by Django 5.0.3 on 2025-03-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activitytracker", "0002_remove_activity_duration_interval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("walking", "Walking"),
                    ("hiking", "Hiking"),
                    ("running", "Running"),
                    ("cycling", "Cycling"),
                    ("swimming", "Swimming"),
                    ("strength_training", "Strength Training"),
                    ("yoga", "Yoga"),
                    ("crossfit", "CrossFit"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="activitytracker.activity",
                    ),
                ),
            ],
        ),
    ]
