# Generated by Django 5.0.3 on 2025-03-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activitytracker", "0004_changehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Optional GPX or FIT file",
                null=True,
                upload_to="activity_files/",
            ),
        ),
    ]
