# Generated by Django 5.0.3 on 2025-03-13 14:38

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activitytracker", "0005_activity_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Optional GPX or FIT file",
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="activity_files/",
            ),
        ),
    ]
