# Generated by Django 5.0.3 on 2025-03-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activitytracker", "0006_alter_activity_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="duration",
            field=models.DurationField(
                help_text="Duration of activity in hh:mm:ss format"
            ),
        ),
    ]
