# Generated by Django 5.1.5 on 2025-04-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activitytracker", "0007_alter_activity_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="file",
        ),
    ]
