# Generated by Django 5.1.5 on 2025-04-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activitytracker", "0008_remove_activity_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("walking", "Walking"),
                    ("hiking", "Hiking"),
                    ("running", "Running"),
                    ("cycling", "Cycling"),
                    ("swimming", "Swimming"),
                    ("strength_training", "Strength Training"),
                    ("yoga", "Yoga"),
                    ("crossfit", "CrossFit"),
                    ("dancing", "Dancing"),
                    ("gym", "Gym"),
                ],
                max_length=20,
            ),
        ),
    ]
